config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :pages
  root "pages#home"

   get "about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end



  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: "Article was successfully deleted."
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>

  <% if @article.errors.any? %>
    <h2>The following errors prohibited this article from being saved:</h2>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
  <p>
    <%= f.label :title %> <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %> <br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render "articles/form" %>
<p>

    <%= link_to 'Cancel and return to articles listing', articles_path %>
</p>

app/views/articles/index.html.erb
<h1>Articles Listing Page</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td>
          <%= link_to 'Show', article_path(article) %> |
          <%= link_to 'Edit', edit_article_path(article) %> |
          <%= link_to 'Delete', article_path(article), data: {turbo_method: :delete,turbo_confirm: "Are you sure"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><%= link_to  'Create new article', new_article_path %></p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= notice %>
<%= render "articles/form" %>
<p>
  <%= link_to 'Return to articles listing', articles_path %>
</p>

app/views/articles/show.html.erb
<h1>Article</h1>
<h2><%= @article.title %></h2>
<p><%= @article.description %></p>

<div class="links">
  <%= link_to 'Back', articles_path %> |
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Delete', article_path(@article), data: {turbo_method: :delete,turbo_confirm: "Are you sure"} %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Omegablog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= notice %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

  <%= link_to 'Articles listing', articles_path %> |
  <%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to the Homepage</h1>

  <%= link_to 'Articles listing', articles_path %> |
  <%= link_to 'About page', about_path %>